# -*- coding: utf-8 -*-
"""week2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c80GabWGPx4Xi4j5uavndFDXqHQ699MP
"""

from collections import defaultdict

def solution(graph, start):
    # 그래프를 인접 리스트로 변환
    adj_list = defaultdict(list)
    for u, v in graph:
        adj_list[u].append(v)

    visited = set()
    result = []

    # DFS 탐색
    def dfs(node):
        visited.add(node)
        result.append(node)

        for neighbor in adj_list.get(node, []):
            if neighbor not in visited:
                dfs(neighbor)

    # 3. 시작 노드부터 DFS 실행
    dfs(start)

    return result

graph = [
        ('A', 'B'),
        ('A', 'C'),
        ('B', 'D'),
        ('B', 'E'),
        ('C', 'F'),
        ('E','F')
    ]
start = 'A'

print(solution(graph, start))

from collections import defaultdict, deque

def solution(graph, start):
    # 그래프를 인접 리스트로 변환(생성)
    adj_list = defaultdict(list)
    for u, v in graph:
        adj_list[u].append(v)

    visited = set()
    result = []

    # BFS를 위한 큐
    queue = deque([start])
    visited.add(start)

    # BFS 탐색
    while queue:
        node = queue.popleft()
        result.append(node)

        for neighbor in adj_list.get(node, []):
            if neighbor not in visited:
                visited.add(neighbor)
                queue.append(neighbor)

    return result

graph = [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 0)]

print(solution(graph, 1))

from collections import deque

## bfs를 사용하기 위해 deque 사용
## solution  함수
def solution(maps):

		## 맵 크기 지정
    n, m = len(maps), len(maps[0])

    ## 이동 방향 정의 : 상, 하, 좌, 우
    directions = [(-1,0), (1,0), (0,-1), (0,1)]

		## bfs 큐 초기화
    queue = deque()
    queue.append((0, 0))  # 시작 위치

	 ## bfs 탐색 시작 -> 가까운 칸부터 탐색
    while queue:
        x, y = queue.popleft()

				## 현재 위치에서 상,하,좌,우 이동
        for dx, dy in directions:
            nx, ny = x + dx, y + dy

            # 맵 범위 안이고, (이동 가능하고 아직 방문 안한 곳 = 1)한 경우
            if 0 <= nx < n and 0 <= ny < m and maps[nx][ny] == 1:
                ##  0 -> 벽, 1 -> 길 + 미방문, 2이상 -> 이미 방문한 칸
                maps[nx][ny] = maps[x][y] + 1  # 거리 누적
                queue.append((nx, ny))

    # 도착 지점 확인
    return maps[n-1][m-1] if maps[n-1][m-1] != 1 else -1