# -*- coding: utf-8 -*-
"""week6_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gdKJCgRl9zhsfpdRQY0AdX_rQUElk4Io
"""

import heapq

def solution(graph, start):
    """
    graph: dict 형태로 주어진다고 함.
      예) {'A': {'B': 9, 'C': 3}, 'B': {'A': 5}, 'C': {'B': 1}}
    start: 출발 노드 (문자열)

    return:
      (distance_dict, path_dict)
      distance_dict: 시작 노드부터 각 노드까지 최소 비용
      path_dict: 각 노드까지 최단 경로 (노드 리스트)
    """

    INF = 10**18

    # 그래프에 등장하는 모든 노드 수집 (키로만 있거나, 이웃으로만 등장하는 노드 -> 출발 노드가 아니고 도착 노드로만 등장할 수도 있기에)
    nodes = set(graph.keys())
    for u in graph:
        for v in graph[u]:
            nodes.add(v)

    dist = {node: INF for node in nodes}
    prev = {node: None for node in nodes}
    dist[start] = 0
    prev[start] = start  # 경로 출력에서 시작노드는 [start]가 되게 하려고 start로 표시

    pq = [(0, start)]  # (거리, 노드)

    while pq:
        cur_dist, u = heapq.heappop(pq)

        # 이미 더 좋은 값으로 처리된 적 있으면 스킵
        if cur_dist != dist[u]:
            continue

        # 최단 거리를 갱신하는 for문
        for v, w in graph.get(u, {}).items():
            nd = cur_dist + w
            if nd < dist[v]:
                dist[v] = nd
                prev[v] = u
                heapq.heappush(pq, (nd, v))

    # 최단 경로 리스트로 복원
    def build_path(target):
        if dist[target] == INF:
            return []  # 도달 불가면 빈 경로 (문제에서 도달 불가 케이스 언급은 없지만 안전하게)
        if target == start:
            return [start]

        path = []
        cur = target
        while cur is not None and cur != start:
            path.append(cur)
            cur = prev[cur]

        path.append(start)
        path.reverse()
        return path

    paths = {node: build_path(node) for node in nodes}

    # 보기 좋게: 시작 노드를 포함해 dist/paths 둘 다 start 기준으로 정렬 출력하고 싶다면
    # 여기서는 입력 노드 그대로 dict 반환
    return dist, paths


if __name__ == "__main__":
    graph = {
        'A': {'B': 9, 'C': 3},
        'B': {'A': 5},
        'C': {'B': 1}
    }
    print(solution(graph, 'A'))