# -*- coding: utf-8 -*-
"""week6_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gdKJCgRl9zhsfpdRQY0AdX_rQUElk4Io
"""

def solution(graph, source):
    """
    graph: 리스트 형태
      graph[u] = [(v, w), (v2, w2), ...]
    source: 시작 노드 (정수)

    return:
      [distance_list, predecessor_list]
      음수 사이클 존재 시 [-1]
    """

    n = len(graph)
    INF = 10**18

    dist = [INF] * n
    pred = [None] * n
    dist[source] = 0
    pred[source] = None

    # V-1번 relax
    for _ in range(n - 1):
        updated = False
        for u in range(n):
            if dist[u] == INF:
                continue
            for v, w in graph[u]:
                if dist[u] + w < dist[v]:
                    dist[v] = dist[u] + w
                    pred[v] = u
                    updated = True
        if not updated:
            break  # 더 이상 갱신 없으면 조기 종료

    # 음수 사이클 검사: 한 번 더 relax가 된다면 존재
    for u in range(n):
        if dist[u] == INF:
            continue
        for v, w in graph[u]:
            if dist[u] + w < dist[v]:
                return [-1]

    return [dist, pred]

if __name__ == "__main__":
    graph = [
        [(1, 4), (2, 3), (4, -6)],
        [(3, 5)],
        [(1, 2)],
        [(0, 7), (2, 4)],
        [(2, 2)]
    ]

    print(solution(graph, 0))